import { useCallback, useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { colors, typography } from '@/constants/designSystem';
import { useAuth } from '@/hooks/useAuth';
import { fetchPatientIdForAuthUser } from '@/lib/onboarding/patient';
import { supabase } from '@/lib/supabase';

type Row = {
  week_ending: string;
  narrative_text: string;
  actionable_recommendation: string | null;
  weight_change_lbs: number | null;
  protein_goal_days_hit: number | null;
  training_sessions_completed: number | null;
};

export default function WeeklySummariesScreen() {
  const insets = useSafeAreaInsets();
  const { user } = useAuth();
  const [rows, setRows] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    if (!user?.id) {
      setLoading(false);
      return;
    }
    setLoading(true);
    try {
      const pid = await fetchPatientIdForAuthUser(user.id);
      if (!pid) return;
      const { data, error } = await supabase
        .from('weekly_narratives')
        .select(
          'week_ending, narrative_text, actionable_recommendation, weight_change_lbs, protein_goal_days_hit, training_sessions_completed',
        )
        .eq('patient_id', pid)
        .order('week_ending', { ascending: false })
        .limit(24);
      if (error || !data) {
        setRows([]);
        return;
      }
      setRows(
        (data as Record<string, unknown>[]).map((r) => ({
          week_ending: String(r.week_ending),
          narrative_text: String(r.narrative_text),
          actionable_recommendation:
            r.actionable_recommendation != null ? String(r.actionable_recommendation) : null,
          weight_change_lbs: r.weight_change_lbs != null ? Number(r.weight_change_lbs) : null,
          protein_goal_days_hit:
            r.protein_goal_days_hit != null ? Number(r.protein_goal_days_hit) : null,
          training_sessions_completed:
            r.training_sessions_completed != null ? Number(r.training_sessions_completed) : null,
        })),
      );
    } finally {
      setLoading(false);
    }
  }, [user?.id]);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <ScrollView
      style={styles.screen}
      contentContainerStyle={{
        paddingTop: insets.top + 16,
        paddingBottom: insets.bottom + 28,
        paddingHorizontal: 20,
      }}>
      <Text style={styles.title}>Past weekly summaries</Text>
      <Text style={styles.sub}>Generated by My Coach from your logs. New weeks appear after the first open each week.</Text>
      {loading ? <Text style={styles.meta}>Loading…</Text> : null}
      {rows.map((r) => (
        <View key={r.week_ending} style={styles.card}>
          <Text style={styles.week}>Week ending {r.week_ending}</Text>
          {r.weight_change_lbs != null ? (
            <Text style={styles.meta}>Weight trend: {r.weight_change_lbs > 0 ? '+' : ''}{r.weight_change_lbs.toFixed(1)} lb</Text>
          ) : null}
          {r.protein_goal_days_hit != null ? (
            <Text style={styles.meta}>Protein goal hit: {r.protein_goal_days_hit} / 7 days</Text>
          ) : null}
          {r.training_sessions_completed != null ? (
            <Text style={styles.meta}>Training sessions: {r.training_sessions_completed}</Text>
          ) : null}
          <Text style={styles.body}>{r.narrative_text}</Text>
          {r.actionable_recommendation ? (
            <Text style={styles.rec}>Focus: {r.actionable_recommendation}</Text>
          ) : null}
        </View>
      ))}
      {!loading && rows.length === 0 ? <Text style={styles.meta}>No saved summaries yet.</Text> : null}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.dark },
  title: { ...typography.h2, color: colors.white, marginBottom: 6 },
  sub: { ...typography.body, color: colors.gray1, marginBottom: 16 },
  card: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.goldDim,
    padding: 14,
    marginBottom: 14,
    backgroundColor: colors.darkCard,
  },
  week: { ...typography.body, color: colors.goldLight, fontWeight: '600', marginBottom: 6 },
  meta: { ...typography.body, color: colors.gray2, fontSize: 13, marginBottom: 4 },
  body: { ...typography.body, color: colors.gray1, marginTop: 8, lineHeight: 22 },
  rec: { ...typography.body, color: colors.white, marginTop: 10, fontWeight: '500' },
});
